'use client';
import { useState, useRef } from 'react';
import { Search, Landmark, FileText, Vote, ShieldCheck, BookOpen, ExternalLink, UserRound, Network, Scale, ChevronLeft, ChevronRight, LoaderCircle } from 'lucide-react';
type Item = Record<string, any>;
const tabs=[['perfil','Perfil',UserRound],['propostas','Propostas',FileText],['votos','Votações',Vote],['redes','Redes sociais',Network],['checagens','Checagens',ShieldCheck],['controversias','Controvérsias',Scale]] as const;
async function query(path:string,params:Record<string,string>={}) {const r=await fetch('/api/camara?'+new URLSearchParams({path,...params}));const j=await r.json() as Item;if(!r.ok)throw new Error(j.error);return j;}
function Link({href,children}:{href:string,children:React.ReactNode}) {return <a href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={14}/></a>}
const date=(v:string)=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'Não informado';
export default function Home(){
 const [name,setName]=useState(''),[results,setResults]=useState<Item[]|null>(null),[person,setPerson]=useState<Item|null>(null),[tab,setTab]=useState('perfil'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[data,setData]=useState<Item|null>(null),[loading,setLoading]=useState(false),[detailError,setDetailError]=useState(''),[page,setPage]=useState(1),[year,setYear]=useState(String(new Date().getFullYear())),[method,setMethod]=useState(false);const token=useRef(0);
 async function search(e?:React.FormEvent){e?.preventDefault();if(name.trim().length<2)return;setBusy(true);setError('');try{const j=await query('deputados',{nome:name.trim(),itens:'100',ordenarPor:'nome',ordem:'ASC'});setResults(j.dados);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function select(p:Item){token.current++;setPerson(p);setResults(null);setTab('perfil');setData(null);setPage(1);load(p,'perfil',1,year);}
 async function load(p:Item,t:string,pg:number,y:string){const id=++token.current;setLoading(true);setDetailError('');setData(null);try{
 let j:Item;
 if(t==='perfil'){const profile=await query('deputados/'+p.id);const extra=await Promise.allSettled([query('deputados/'+p.id+'/profissoes'),query('deputados/'+p.id+'/orgaos',{itens:'100'})]);j={...profile,profissoes:extra[0].status==='fulfilled'?extra[0].value.dados:null,orgaos:extra[1].status==='fulfilled'?extra[1].value.dados:null};}
 else if(t==='propostas')j=await query('proposicoes',{idDeputadoAutor:String(p.id),ano:y,itens:'12',pagina:String(pg),ordenarPor:'id',ordem:'DESC'});
 else if(t==='votos'){const end=new Date(),start=new Date();start.setDate(start.getDate()-30);const list=await query('votacoes',{itens:'20',pagina:String(pg),dataInicio:start.toISOString().slice(0,10),dataFim:end.toISOString().slice(0,10),ordenarPor:'dataHoraRegistro',ordem:'DESC'});const votes=await Promise.allSettled((list.dados as Item[]).map(async(v:Item)=>{const r=await query('votacoes/'+v.id+'/votos');return {...v,voto:r.dados.find((x:Item)=>Number(x.deputado_?.id??x.deputado?.id)===Number(p.id))?.tipoVoto,source:r.source}}));j={...list,dados:votes.flatMap(r=>r.status==='fulfilled'&&r.value.voto?[r.value]:[]),failed: votes.filter(r=>r.status==='rejected').length,scanned:list.dados.length};}
 else if(t==='redes')j=await query('deputados/'+p.id);
 else j={dados:[]};
 if(id===token.current)setData(j);
 }catch(e){if(id===token.current)setDetailError((e as Error).message)}finally{if(id===token.current)setLoading(false)}}
 function switchTab(t:string){setTab(t);setPage(1);if(person)load(person,t,1,year)}
 function paginate(pg:number){setPage(pg);if(person)load(person,tab,pg,year)}
 const profile=data?.dados;const stamp=data?.consultedAt;
 return <div className="app"><header><div className="brand"><span className="brand-icon"><Landmark size={23}/></span><span>radar<span className="brand-light">público</span></span></div><div className="header-right"><span className="version">Primeira versão · Câmara</span><button className="plain" onClick={()=>setMethod(!method)}><BookOpen size={17}/> Como funciona</button></div></header>
 <div className="shell"><aside className="sidebar"><div className="side-label">CONSULTA PÚBLICA</div><div className="side-active"><Search size={18}/> Explorar políticos</div><div className="side-context"><span className="eyebrow">COBERTURA ATUAL</span><h3>Deputados federais</h3><p>Registros da Câmara dos Deputados. Outros cargos ainda não estão integrados.</p><Link href="https://dadosabertos.camara.leg.br/">Conhecer a fonte</Link></div><div className="side-bottom"><ShieldCheck size={24}/><p>Informação com origem.<br/>Conclusões com contexto.</p></div></aside>
 <main><div className="topline"><span>Explorar / {person?'Ficha parlamentar':'Busca por nome'}</span><span className="source-tag">Fonte oficial</span></div><div className="intro"><div><span className="eyebrow">POLÍTICA À VISTA</span><h1>Conheça quem te representa.</h1><p>Pesquise um nome e consulte a atuação parlamentar nas fontes públicas.</p></div><span className="intro-mark" aria-hidden="true"><Landmark size={48}/></span></div>
 <form onSubmit={search} className="search-box"><Search size={22}/><label className="sr-only" htmlFor="name">Nome do deputado federal</label><input id="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Digite o nome de um deputado federal" minLength={2} required/><button disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:null}{busy?'Consultando…':'Pesquisar'}</button></form><div className="search-help">A busca usa o nome parlamentar cadastrado na Câmara. Escolha a pessoa pelo partido e estado.</div>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>search()}>Tentar novamente</button></div>}
 {results&&<section className="results"><h2>{results.length?`${results.length} resultado${results.length>1?'s':''}`:'Nenhum deputado encontrado'}</h2>{!results.length&&<p>Tente apenas um sobrenome. Prefeitos, senadores e governadores ainda não estão nesta consulta.</p>}<div className="result-grid">{results.map(p=><button key={p.id} className="result" onClick={()=>select(p)}><span className="avatar">{p.nome.slice(0,1)}</span><span><strong>{p.nome}</strong><small>{p.siglaPartido} · {p.siglaUf}</small></span><span className="result-action">Ver ficha</span></button>)}</div></section>}
 {!person&&!results&&<><div className="section-heading"><h2>O que você pode consultar</h2><span>Um nome, várias perspectivas</span></div><div className="overview"><article><UserRound/><span className="card-number">01</span><h3>Quem é</h3><p>Perfil, profissão cadastrada, partido, estado e participação em órgãos.</p><span className="available">Consulta à Câmara</span></article><article><FileText/><span className="card-number">02</span><h3>O que propõe</h3><p>Ementas das proposições de autoria ou coautoria, por ano, com paginação.</p><span className="available">Consulta à Câmara</span></article><article><Vote/><span className="card-number">03</span><h3>Como vota</h3><p>Votos individuais encontrados em uma amostra de votações dos últimos 30 dias.</p><span className="available">Amostra recente</span></article></div><div className="coverage-panel"><div><ShieldCheck size={25}/><h3>Uma fonte para cada informação</h3><p>Checagens e controvérsias terão evidências, datas e situação de cada caso. Essas bases ainda não estão conectadas.</p></div><button className="plain" onClick={()=>setMethod(true)}>Ver metodologia</button></div></>}
 {person&&<section className="dossier"><div className="person-header"><span className="avatar large">{person.nome.slice(0,1)}</span><div><span className="eyebrow">FICHA PARLAMENTAR · ID {person.id}</span><h2>{person.nome}</h2><p>{person.siglaPartido} · {person.siglaUf} <span>Deputado(a) federal · cadastro da Câmara</span></p></div><Link href={'https://www.camara.leg.br/deputados/'+person.id}>Perfil oficial</Link></div><nav className="tabs" aria-label="Seções da ficha">{tabs.map(([k,label,Icon])=><button key={k} className={tab===k?'selected':''} onClick={()=>switchTab(k)} aria-current={tab===k?'page':undefined}><Icon size={17}/>{label}</button>)}</nav><div className="tab-content">
 {tab==='propostas'&&<div className="section-heading"><div><h2>Proposições com autoria registrada</h2><p>Inclui coautorias. A lista não equivale a leis aprovadas.</p></div><label>Ano <select value={year} onChange={e=>{setYear(e.target.value);setPage(1);load(person,tab,1,e.target.value)}}>{Array.from({length:28},(_,i)=>String(new Date().getFullYear()-i)).map(y=><option key={y}>{y}</option>)}</select></label></div>}
 {tab==='votos'&&<><h2>Como votou recentemente</h2><p className="note">Amostra: até 20 votações por página, nos últimos 30 dias. Votações simbólicas não identificam votos individuais. Não encontrar um voto nesta amostra não significa ausência ou abstenção.</p></>}
 {loading&&<div className="loading" role="status"><LoaderCircle className="spin"/>Consultando registros da Câmara…</div>}{detailError&&<div className="error" role="alert">{detailError}<button onClick={()=>load(person,tab,page,year)}>Tentar novamente</button></div>}
 {!loading&&data&&tab==='perfil'&&<><div className="profile-grid">{[['Nome civil',profile.nomeCivil],['Situação no registro',profile.ultimoStatus?.situacao],['Partido / estado',`${profile.ultimoStatus?.siglaPartido||person.siglaPartido} / ${profile.ultimoStatus?.siglaUf||person.siglaUf}`],['Escolaridade',profile.escolaridade],['Nascimento',date(profile.dataNascimento)],['Município de nascimento',`${profile.municipioNascimento||'Não informado'} ${profile.ufNascimento||''}`],['Profissão cadastrada',data.profissoes===null?'Consulta indisponível':data.profissoes?.map((x:Item)=>x.titulo??x.profissao??x.nome).filter(Boolean).join(', ')||'Não informada pela fonte']].map(([label,value])=><div key={label}><small>{label}</small><strong>{value||'Não informado'}</strong></div>)}</div><h3>Órgãos e comissões cadastrados</h3>{data.orgaos===null?<p>Consulta indisponível.</p>:data.orgaos?.length?<div className="orgs">{data.orgaos.map((x:Item,i:number)=><div key={i}><strong>{x.nome||x.sigla}</strong><span>{x.titulo||''}{x.dataFim?` · até ${date(x.dataFim)}`:''}</span></div>)}</div>:<p>Nenhum registro retornado pela fonte.</p>}</>}
 {!loading&&data&&tab==='propostas'&&<>{data.dados.map((p:Item)=><article className="proposal" key={p.id}><span className="type">{p.siglaTipo}</span><div><h3>{p.siglaTipo} {p.numero}/{p.ano}</h3><p>{p.ementa||'Ementa não informada.'}</p><Link href={'https://www.camara.leg.br/propostas-legislativas/'+p.id}>Ementa e tramitação oficial</Link></div></article>)}{!data.dados.length&&<p className="empty">Nenhuma proposição retornada para este ano e página.</p>}</>}
 {!loading&&data&&tab==='votos'&&<>{data.failed>0&&<div className="error">{data.failed} consultas de votos falharam. A amostra está incompleta.</div>}<small className="muted">{data.scanned} registros de votação consultados nesta página.</small>{data.dados.map((v:Item)=><article className="vote-row" key={v.id}><div><small>{date(v.data)} · {v.siglaOrgao||'Câmara'}</small><h3>{v.descricao||'Descrição não informada pela Câmara'}</h3><p>Objeto votado: consulte o registro para distinguir texto, parecer, emenda ou destaque.</p><Link href={v.source}>Registro e votos na Câmara</Link></div><span className={'vote-badge '+(v.voto==='Sim'?'yes':v.voto==='Não'?'no':'')}>{v.voto}</span></article>)}{!data.dados.length&&<p className="empty">Nenhum voto individual deste parlamentar foi encontrado nesta página da amostra. Você pode consultar a próxima página.</p>}</>}
 {!loading&&data&&['propostas','votos'].includes(tab)&&<div className="pagination"><button disabled={page===1} onClick={()=>paginate(page-1)}><ChevronLeft size={17}/>Anterior</button><span>Página {page}</span><button disabled={!data.links?.some((l:Item)=>l.rel==='next')} onClick={()=>paginate(page+1)}>Próxima<ChevronRight size={17}/></button></div>}
 {!loading&&data&&tab==='redes'&&<><h2>Redes informadas pela Câmara</h2><p className="note">Links cadastrados na fonte. Publicações e discursos ainda não são coletados.</p>{profile.redeSocial?.length?<div className="socials">{profile.redeSocial.map((url:string)=><Link key={url} href={url}>{url}</Link>)}</div>:<p className="empty">A fonte não retornou redes sociais para este parlamentar.</p>}{profile.urlWebsite&&<Link href={profile.urlWebsite}>Site cadastrado</Link>}</>}
 {!loading&&data&&['checagens','controversias'].includes(tab)&&<div className="not-connected"><span className="not-icon">{tab==='checagens'?<ShieldCheck size={30}/>:<Scale size={30}/>}</span><span className="eyebrow">COBERTURA AINDA NÃO CONECTADA</span><h2>{tab==='checagens'?'Declarações com evidências':'Casos com contexto'}</h2><p>{tab==='checagens'?'Esta versão ainda não reúne checagens jornalísticas nem analisa discursos. Uma declaração só será apresentada com a fala original, a data, as evidências e a classificação atribuída pela fonte.':'Esta versão ainda não reúne notícias ou processos. Cada caso precisará identificar a pessoa, as fontes, a data e a situação: acusação, investigação, decisão ou recurso.'}</p><div className="note">A falta de registros aqui não indica que não existam {tab==='checagens'?'declarações checadas':'controvérsias'}.</div></div>}
 {stamp&&<div className="data-footer">Consultado em {new Date(stamp).toLocaleString('pt-BR')} · Câmara dos Deputados{data.source&&<Link href={data.source}>Dados da consulta</Link>}</div>}
 </div></section>}
 {method&&<section className="method"><div className="section-heading"><h2>Como funciona</h2><button className="plain" onClick={()=>setMethod(false)}>Fechar</button></div><div className="method-grid"><div><h3>Identidade antes de informação</h3><p>O nome retorna candidatos à busca. Você escolhe a ficha pelo partido e estado; cada consulta usa o identificador único da Câmara.</p></div><div><h3>Fontes e limites visíveis</h3><p>Propostas são paginadas por ano. Votos são uma amostra recente, com a descrição da votação. Registros indisponíveis não são substituídos por exemplos inventados.</p></div><div><h3>Verificação de declarações</h3><p>A futura integração distinguirá afirmações verificáveis de opinião e promessa. Uma classificação terá autor, evidências e método. Não haverá selo automático de “mentira”.</p></div><div><h3>Próximas fontes</h3><p>Senado e TSE ampliarão cargos e histórico eleitoral. Notícias, processos e checagens exigirão coleta própria e revisão antes da publicação.</p></div></div><Link href="https://dadosabertos.camara.leg.br/swagger/api.html">Documentação da fonte oficial</Link></section>}
 <footer><span>Radar Público · protótipo funcional</span><span>Dados públicos. Leitura com contexto.</span></footer></main></div></div>
}
